# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: dev-pull-req

on:
  pull_request:
    branches: [ "development" ]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore ./MVVMDemoNew.sln
    - name: Check format and lint
      run: dotnet format --verify-no-changes --verbosity diagnostic
  test:
    runs-on: windows-latest
    needs: lint
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore ./MVVMDemoNew.sln
    - name: Build
      run: dotnet build ./MVVMDemoNew.sln --no-restore /p:EnableWindowsTargeting=true
    - name: Test
      run: dotnet test ./MVVMDemoNew.Tests/MVVMDemoNew.Tests.csproj --no-build --verbosity normal --logger "trx;LogFileName=extests.trx" --collect:"XPlat Code Coverage"
    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action/windows@v2
      if: always()
      with:
        files: |
          **/MVVMDemoNew.Tests/TestResults/extests.trx
    - name: Combine Coverage Reports
      uses: danielpalme/ReportGenerator-GitHub-Action@5.3.0
      with:
        reports: "**/*.cobertura.xml" 
        targetdir: "${{ github.workspace }}"
        reporttypes: "Cobertura"
        verbosity: "Info"
        title: "Code Coverage"
        tag: "${{ github.run_number }}_${{ github.run_id }}" 
        customSettings: "" 
        toolpath: "reportgeneratortool"
    - name: Publish Code Coverage Report
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: "Cobertura.xml"
        badge: true
        fail_below_min: false # just informative for now
        format: markdown
        hide_branch_rate: false
        hide_complexity: false
        indicators: true
        output: both
        thresholds: "10 30"
    - name: Add Coverage PR Comment
      uses: marocchino/sticky-pull-request-comment@v2
      if: github.event_name == 'pull_request'
      with:
        recreate: true
        path: code-coverage-results.md
        
